name: toit
description: "A Flutter app for automating Toit login and checking order dates. Features include auto-login, date status tracking, and a clean Material Design 3 interface."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI and theming
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^7.3.1

  # State management
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.7

  # Networking and storage
  dio: ^5.4.1
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2

  # Utilities
  logging: ^1.2.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Code generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # App icon generation
  flutter_launcher_icons: ^0.13.1

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
